HomeAssignmentEnterpriseProgramming/HomeAssignmentEnterpriseProgramming/Models/Item.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HomeAssignmentEnterpriseProgramming.Models
{
    public enum QualityEnum {
        Excellent,
        Good,
        Poor,
        Bad
    }
    public class Item
    {
        [Required]
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ItemID { get; set; }

        [Required]
        [Display(Name = "Item Type")]
        public int ItemTypeID { get; set; }

        public ItemType ItemType { get; set; }
      
        public ApplicationUser Owner { get; set; }

        public string ApplicationUserId { get; set; }

        [Range(1, int.MaxValue, ErrorMessage = "The quantity must be 1 or more!")]
        public int Quantity { get; set; }

        [Required]
        public QualityEnum Quality { get; set; }

        [Required]
        [Display(Name="Date Added")]
        public DateTime DateAdded { get; set; }

        [Required]
        [Range(0.0, (double)decimal.MaxValue, ErrorMessage = "The price must be 0 or more!")]
        public decimal Price { get; set; }
    }
}

HomeAssignmentEnterpriseProgramming/HomeAssignmentEnterpriseProgramming/Models/ItemType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace HomeAssignmentEnterpriseProgramming.Models
{
    public class ItemType
    {

        public ItemType()
        {
            this.Items = new HashSet<Item>();
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Reference { get; set; }

        //[Required]
        [Display(Name = "Category ID")]
        public int CategoryID { get; set; }

        public Category Category { get; set; }

        [Required]
        [Display(Name = "Item Type Name")]
        public String Name { get; set; }

        [Display(Name = "Upload Image")]
        public String ImageURL { get; set; }

        [Display(Name = "Item Type")]
        public virtual ICollection<Item> Items { get; set; }

    }
}

HomeAssignmentEnterpriseProgramming/HomeAssignmentEnterpriseProgramming/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using HomeAssignmentEnterpriseProgramming.Models;

namespace HomeAssignmentEnterpriseProgramming.Controllers
{
    public class ItemsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Items
        [AllowAnonymous]
        public ActionResult Index(string search, int? page, string sortBy)
        {
            ViewBag.SortDateParameter = string.IsNullOrEmpty(sortBy) ? "Newest First" : "";

            var items = db.Items.AsQueryable().Include(i => i.ItemType);
            items = items.Include(i=>i.Owner);
            items = items.Where(x=>x.Owner.UserName.StartsWith(search) || search==null);

            switch (sortBy)
            {
                case "Newest First": items = items.OrderByDescending(x => x.DateAdded);
                    break;
                default: items = items.OrderBy(x=>x.DateAdded);
                    break;
            }

            return View(items.ToList().ToPagedList(page ?? 1, 5));
        }

        public ActionResult ItemPartialView(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Item item = db.Items.Find(id);
            item.Owner = db.Users.FirstOrDefault(i => i.Id == item.ApplicationUserId);
            item.ItemType = db.ItemTypes.FirstOrDefault(i => i.Reference == item.ItemTypeID);

            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // GET: Items/Details/5
        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Item item = db.Items.Find(id);
            item.Owner = db.Users.FirstOrDefault(i => i.Id == item.ApplicationUserId);
            item.ItemType = db.ItemTypes.FirstOrDefault(i => i.Reference == item.ItemTypeID);

            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // GET: Items/Create
        [Authorize()]

        public ActionResult Create()
        {
            ViewBag.ItemTypeID = new SelectList(db.ItemTypes, "Reference", "Name");
            return View();
        }

        // POST: Items/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize()]
        public ActionResult Create([Bind(Include = "ItemID,ItemTypeID,Owner,ApplicationUserId,Quantity,Quality,Price,DateAdded")] Item item)
        {
            var owner = db.Users.FirstOrDefault(u=>u.UserName==User.Identity.Name);
            item.Owner = owner;
            item.ApplicationUserId = owner.Id;
            item.Owner.Items.Add(item);
            item.DateAdded = DateTime.Now;

            if (ModelState.IsValid)
            {
                if (db.Items.SingleOrDefault(x=> x.ItemTypeID == item.ItemTypeID && x.ApplicationUserId == item.ApplicationUserId && x.Quality == item.Quality && x.Price == item.Price) == null)
                {
                    item.ItemType = db.ItemTypes.FirstOrDefault(i => i.Reference == item.ItemTypeID);
                    item.ItemType.Items.Add(item);
                    db.Items.Add(item);

                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.Error = "You've already put this item on sale! Try adding more to its quantity by editing it.";
                }
            }

            ViewBag.ItemTypeID = new SelectList(db.ItemTypes, "Reference", "Name", item.ItemTypeID);
            return View(item);

        }

        // GET: Items/Edit/5
        [Authorize()]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Item item = db.Items.Find(id);
            item.Owner = db.Users.FirstOrDefault(i => i.Id == item.ApplicationUserId);

            if (User.Identity.Name == item.Owner.UserName)
            {
                if (item == null)
                {
                    return HttpNotFound();
                }

                ViewBag.ItemTypeID = new SelectList(db.ItemTypes, "Reference", "Name");

                return View(item);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        // POST: Items/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize()]
        public ActionResult Edit([Bind(Include = "ItemID,ItemTypeID,Owner,ApplicationUserId,Quantity,Quality,Price,DateAdded")] Item item)
        {
            var owner = db.Users.FirstOrDefault(u => u.UserName == User.Identity.Name);
            item.Owner = owner;
            item.ApplicationUserId = owner.Id;
            item.Owner.Items.Add(item);
            item.DateAdded = DateTime.Now;

            if (ModelState.IsValid)
            {
                db.Entry(item).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ItemTypeID = new SelectList(db.ItemTypes, "Reference", "Name", item.ItemTypeID);

            return View(item);
        }

        // GET: Items/Delete/5
        [Authorize()]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            item.Owner = db.Users.FirstOrDefault(i => i.Id == item.ApplicationUserId);

            if (User.Identity.Name == item.Owner.UserName)
            {
                if (item == null)
                {
                    return HttpNotFound();
                }
                return View(item);
            }
            else
            {
                ViewBag.Error = "That doesn't belong to you!";
                return RedirectToAction("Index");
            }
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize()]
        public ActionResult DeleteConfirmed(int id)
        {
            Item item = db.Items.Find(id);
            db.Items.Remove(item);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HomeAssignmentEnterpriseProgramming/HomeAssignmentEnterpriseProgramming/Views/Items/Create.cshtml
@model HomeAssignmentEnterpriseProgramming.Models.Item

@{
    ViewBag.Title = "Create";
}

<h2>Register a new Item for Sale</h2>

@if (ViewBag.Message != null)
{
    <div class="alert alert-success" role="alert">
        @ViewBag.Message
    </div>
}

@if (ViewBag.Error != null)
{
    <div class="alert alert-danger" role="alert">
        @ViewBag.Error
    </div>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Item</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ItemTypeID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ItemTypeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ItemTypeID, "", new { @class = "text-danger" })
            </div>
        </div>

       
        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quality, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Quality, "Select Quality", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Quality, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HomeAssignmentEnterpriseProgramming/HomeAssignmentEnterpriseProgramming/Views/Items/Delete.cshtml
@model HomeAssignmentEnterpriseProgramming.Models.Item

@{
    ViewBag.Title = "Delete";
}

<h2>Remove Item from Sale</h2>

@if (ViewBag.Message != null)
{
    <div class="alert alert-success" role="alert">
        @ViewBag.Message
    </div>
}

@if (ViewBag.Error != null)
{
    <div class="alert alert-danger" role="alert">
        @ViewBag.Error
    </div>
}

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ItemTypeID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemTypeID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Owner)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Owner)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quality)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quality)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

HomeAssignmentEnterpriseProgramming/HomeAssignmentEnterpriseProgramming/Views/Items/Details.cshtml
@model HomeAssignmentEnterpriseProgramming.Models.Item

@{
    ViewBag.Title = "Details";
}

<h2>Details of Item</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ItemType.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemType.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Owner)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Owner.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quality)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quality)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateAdded)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateAdded)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.ItemType.ImageURL)
        </dt>

        <dd>
            <img src="@Model.ItemType.ImageURL" style="height:100px; width:130px" />
        </dd>*@

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ItemID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

HomeAssignmentEnterpriseProgramming/HomeAssignmentEnterpriseProgramming/Views/Items/Edit.cshtml
@model HomeAssignmentEnterpriseProgramming.Models.Item

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Item on Sale</h2>

@if (ViewBag.Message != null)
{
    <div class="alert alert-success" role="alert">
        @ViewBag.Message
    </div>
}

@if (ViewBag.Error != null)
{
    <div class="alert alert-danger" role="alert">
        @ViewBag.Error
    </div>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ItemID)

        <div class="form-group">
            @Html.LabelFor(model => model.ItemTypeID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ItemTypeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ItemTypeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quality, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Quality, "Select Quality", new { @class = "form-control" });
                @Html.ValidationMessageFor(model => model.Quality, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HomeAssignmentEnterpriseProgramming/HomeAssignmentEnterpriseProgramming/Views/Items/Index.cshtml
@using PagedList
@using PagedList.Mvc

@model IPagedList<HomeAssignmentEnterpriseProgramming.Models.Item>

@{
    ViewBag.Title = "Index";
}

<h2>List of Items on Sale</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<div class="row">
    <div class="col-sm-10">
        <p>
            @using (Html.BeginForm("Index", "Items", FormMethod.Get))
            {
                <b>Search by Name</b>
                @Html.TextBox("search") <input type="submit" value="Search" />
            }
        </p>
    </div>

    <div class="col-sm-2">
            @Html.ActionLink("Sort Newest First", "Index", new { sortBy = ViewBag.SortDateParameter, searchBy = Request.QueryString["searchBy"], search = Request["search"] })
    </div>
</div>

    <div class="container-fluid">
        <div class="row">


            @foreach (var item in Model)
            {<div class="col-sm-4">

                    @Html.Partial("_ItemPartialView", item)
                    <br />
                </div>
            }

        </div>

        @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
    </div>

HomeAssignmentEnterpriseProgramming/HomeAssignmentEnterpriseProgramming/Views/Items/_ItemPartialView.cshtml
@model HomeAssignmentEnterpriseProgramming.Models.Item 

    
        <div class="card">
            <div class="card-body">
                <div class="card-title" style="font-weight:bold;">
                    @Html.DisplayNameFor(model => model.ItemType.Name): @Html.DisplayFor(model => model.ItemType.Name)
                </div>

                <div class="col-12">
                    <p><b>@Html.DisplayNameFor(model => model.Owner)</b>: @Html.DisplayFor(model => model.Owner.Email)</p>
                    <p><b>@Html.DisplayNameFor(model => model.Quantity)</b>: @Html.DisplayFor(model => model.Quantity)</p>
                    <p><b>@Html.DisplayNameFor(model => model.Quality)</b>: @Html.DisplayFor(model => model.Quality)</p>
                    <p><b>@Html.DisplayNameFor(model => model.Price)</b>: €@Html.DisplayFor(model => model.Price)</p>
                    <p><b>@Html.DisplayNameFor(model => model.DateAdded)</b>: @Html.DisplayFor(model => model.DateAdded)</p>

                    <div class="row">
                        <button class="btn btn-outline-primary" style="margin:5px">
                            @Html.ActionLink("Details", "Details", new { id = Model.ItemID })
                        </button>
                        @if (User.Identity.Name == Model.Owner.UserName)
                        {
                        <button class="btn btn-outline-primary" style="margin:5px">
                            @Html.ActionLink("Edit", "Edit", new { id = Model.ItemID })
                        </button>

                        <button class="btn btn-outline-primary" style="margin:5px">
                            @Html.ActionLink("Delete", "Delete", new { id = Model.ItemID })
                        </button>
                        }
                    </div>
                </div>
            </div>
        </div>